### ISSUE TITLE
arrivals is not a function

### ISSUE THREAD

**Issue by Alexander17101** [juliuste/oebb-hafas#2]
When calling the arrivals method it is not being found.
![error](https://user-images.githubusercontent.com/14953567/90149836-41a5df80-dd85-11ea-9e64-7e9d5697b975.png)
![code](https://user-images.githubusercontent.com/14953567/90149840-42d70c80-dd85-11ea-9043-1ac56d66e664.png)

**Comment by juliuste** [comment]
Hey 🙂, thanks for reporting this!

Turns out this lib still used a really outdated version of the underling library called [`hafas-client`](https://github.com/public-transport/hafas-client) while accidentally linking to that lib's _latest_ docs, so that the docs were out of sync with the actual code. Bumped the dependency and released this as `5.0.0` on npm. So running `npm i oebb-hafas@latest` should do the trick. Please re-open if this didn't fix the issue 🙃

**Comment by Alexander17101** [comment]
thanks for the quick fix :)

and there is one other thing: the departures are often time shifted by an hour or so. Is this my failure or is this a maybe problem by you or the hafas-client itself?
